<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PSMProductSeeder extends Seeder
{
    public function run()
    {
        // Clear existing products
        DB::connection('psm')->table('psm_product')->delete();

        $products = [
            // EquipmentPro Solutions Products (Equipment)
            [
                'prod_id' => 'PROD00001',
                'prod_vendor' => 'VEND00001',
                'prod_name' => 'Industrial Air Compressor 5HP',
                'prod_price' => 45000.00,
                'prod_stock' => 8,
                'prod_type' => 'equipment',
                'prod_warranty' => '2 years',
                'prod_expiration' => null,
                'prod_desc' => 'Heavy-duty industrial air compressor with 5HP motor, suitable for various manufacturing applications.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00002',
                'prod_vendor' => 'VEND00001',
                'prod_name' => 'CNC Milling Machine',
                'prod_price' => 285000.00,
                'prod_stock' => 3,
                'prod_type' => 'equipment',
                'prod_warranty' => '3 years',
                'prod_expiration' => null,
                'prod_desc' => 'Precision CNC milling machine with automatic tool changer and digital controls.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00003',
                'prod_vendor' => 'VEND00001',
                'prod_name' => 'Industrial Welding Machine',
                'prod_price' => 32000.00,
                'prod_stock' => 12,
                'prod_type' => 'equipment',
                'prod_warranty' => '18 months',
                'prod_expiration' => null,
                'prod_desc' => 'Heavy-duty welding machine with multiple welding modes and safety features.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00004',
                'prod_vendor' => 'VEND00001',
                'prod_name' => 'Hydraulic Press 20-Ton',
                'prod_price' => 89000.00,
                'prod_stock' => 5,
                'prod_type' => 'equipment',
                'prod_warranty' => '2 years',
                'prod_expiration' => null,
                'prod_desc' => '20-ton hydraulic press for metal forming and fabrication applications.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // OfficeSupplies Depot Products (Supplies)
            [
                'prod_id' => 'PROD00005',
                'prod_vendor' => 'VEND00002',
                'prod_name' => 'Premium Bond Paper A4 (500 sheets)',
                'prod_price' => 250.00,
                'prod_stock' => 150,
                'prod_type' => 'supplies',
                'prod_warranty' => 'no warranty',
                'prod_expiration' => '2026-12-31',
                'prod_desc' => 'High-quality A4 bond paper, 80gsm, perfect for office documents and printing.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00006',
                'prod_vendor' => 'VEND00002',
                'prod_name' => 'Executive Ballpoint Pens (12 pcs)',
                'prod_price' => 180.00,
                'prod_stock' => 80,
                'prod_type' => 'supplies',
                'prod_warranty' => 'no warranty',
                'prod_expiration' => '2027-06-30',
                'prod_desc' => 'Smooth-writing ballpoint pens with comfortable grip, black ink.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00007',
                'prod_vendor' => 'VEND00002',
                'prod_name' => 'Stapler Heavy Duty',
                'prod_price' => 450.00,
                'prod_stock' => 25,
                'prod_type' => 'supplies',
                'prod_warranty' => '1 year',
                'prod_expiration' => null,
                'prod_desc' => 'Heavy-duty stapler capable of stapling up to 50 sheets.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00008',
                'prod_vendor' => 'VEND00002',
                'prod_name' => 'Document Filing Cabinet 4-Drawer',
                'prod_price' => 5200.00,
                'prod_stock' => 15,
                'prod_type' => 'supplies',
                'prod_warranty' => '2 years',
                'prod_expiration' => null,
                'prod_desc' => 'Steel filing cabinet with 4 drawers, lockable, perfect for document organization.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00009',
                'prod_vendor' => 'VEND00002',
                'prod_name' => 'Whiteboard Marker Set (8 colors)',
                'prod_price' => 120.00,
                'prod_stock' => 60,
                'prod_type' => 'supplies',
                'prod_warranty' => 'no warranty',
                'prod_expiration' => '2026-08-15',
                'prod_desc' => 'Non-toxic whiteboard markers with 8 vibrant colors.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00010',
                'prod_vendor' => 'VEND00002',
                'prod_name' => 'Desktop Organizer Set',
                'prod_price' => 850.00,
                'prod_stock' => 30,
                'prod_type' => 'supplies',
                'prod_warranty' => 'no warranty',
                'prod_expiration' => null,
                'prod_desc' => 'Complete desktop organizer with pen holder, letter tray, and document slots.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ModernFurniture Co. Products (Furniture)
            [
                'prod_id' => 'PROD00011',
                'prod_vendor' => 'VEND00003',
                'prod_name' => 'Ergonomic Office Chair',
                'prod_price' => 7500.00,
                'prod_stock' => 20,
                'prod_type' => 'furniture',
                'prod_warranty' => '3 years',
                'prod_expiration' => null,
                'prod_desc' => 'Premium ergonomic office chair with lumbar support and adjustable height.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00012',
                'prod_vendor' => 'VEND00003',
                'prod_name' => 'Executive Desk 160cm',
                'prod_price' => 12500.00,
                'prod_stock' => 12,
                'prod_type' => 'furniture',
                'prod_warranty' => '5 years',
                'prod_expiration' => null,
                'prod_desc' => 'Spacious executive desk with built-in cable management and drawer.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00013',
                'prod_vendor' => 'VEND00003',
                'prod_name' => 'Conference Table 8-Seater',
                'prod_price' => 28500.00,
                'prod_stock' => 6,
                'prod_type' => 'furniture',
                'prod_warranty' => '5 years',
                'prod_expiration' => null,
                'prod_desc' => 'Elegant conference table suitable for 8 persons with premium finish.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00014',
                'prod_vendor' => 'VEND00003',
                'prod_name' => 'Office Visitor Chairs (Set of 4)',
                'prod_price' => 9800.00,
                'prod_stock' => 8,
                'prod_type' => 'furniture',
                'prod_warranty' => '2 years',
                'prod_expiration' => null,
                'prod_desc' => 'Comfortable visitor chairs with modern design, sold in sets of 4.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00015',
                'prod_vendor' => 'VEND00003',
                'prod_name' => 'Filing Cabinet with Lock',
                'prod_price' => 6800.00,
                'prod_stock' => 15,
                'prod_type' => 'furniture',
                'prod_warranty' => '3 years',
                'prod_expiration' => null,
                'prod_desc' => 'Two-drawer filing cabinet with security lock and smooth-gliding drawers.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // AutoParts Express Products (Automotive)
            [
                'prod_id' => 'PROD00016',
                'prod_vendor' => 'VEND00004',
                'prod_name' => 'Synthetic Engine Oil 5W-30 (1L)',
                'prod_price' => 650.00,
                'prod_stock' => 100,
                'prod_type' => 'automotive',
                'prod_warranty' => 'no warranty',
                'prod_expiration' => '2026-05-20',
                'prod_desc' => 'Full synthetic engine oil for gasoline engines, 1-liter bottle.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00017',
                'prod_vendor' => 'VEND00004',
                'prod_name' => 'Car Battery 12V 60Ah',
                'prod_price' => 4800.00,
                'prod_stock' => 25,
                'prod_type' => 'automotive',
                'prod_warranty' => '18 months',
                'prod_expiration' => '2025-11-30',
                'prod_desc' => 'Maintenance-free car battery with high cranking power.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00018',
                'prod_vendor' => 'VEND00004',
                'prod_name' => 'Brake Pad Set (Front)',
                'prod_price' => 1200.00,
                'prod_stock' => 40,
                'prod_type' => 'automotive',
                'prod_warranty' => '1 year',
                'prod_expiration' => null,
                'prod_desc' => 'Premium ceramic brake pads for front wheels, most models available.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00019',
                'prod_vendor' => 'VEND00004',
                'prod_name' => 'Air Filter (Universal)',
                'prod_price' => 350.00,
                'prod_stock' => 75,
                'prod_type' => 'automotive',
                'prod_warranty' => 'no warranty',
                'prod_expiration' => null,
                'prod_desc' => 'High-flow air filter for improved engine performance.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00020',
                'prod_vendor' => 'VEND00004',
                'prod_name' => 'Car Tire 195/65R15',
                'prod_price' => 3200.00,
                'prod_stock' => 50,
                'prod_type' => 'automotive',
                'prod_warranty' => '3 years',
                'prod_expiration' => '2028-03-15',
                'prod_desc' => 'All-season radial tire with excellent grip and durability.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00021',
                'prod_vendor' => 'VEND00004',
                'prod_name' => 'Spark Plug Set (4 pcs)',
                'prod_price' => 850.00,
                'prod_stock' => 60,
                'prod_type' => 'automotive',
                'prod_warranty' => '6 months',
                'prod_expiration' => null,
                'prod_desc' => 'Iridium spark plugs for better fuel efficiency and performance.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00022',
                'prod_vendor' => 'VEND00004',
                'prod_name' => 'Windshield Wiper Blades (Pair)',
                'prod_price' => 550.00,
                'prod_stock' => 80,
                'prod_type' => 'automotive',
                'prod_warranty' => '6 months',
                'prod_expiration' => null,
                'prod_desc' => 'Premium windshield wiper blades for clear visibility in all weather conditions.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'prod_id' => 'PROD00023',
                'prod_vendor' => 'VEND00004',
                'prod_name' => 'Car Air Freshener (6 pcs)',
                'prod_price' => 180.00,
                'prod_stock' => 120,
                'prod_type' => 'automotive',
                'prod_warranty' => 'no warranty',
                'prod_expiration' => '2026-12-31',
                'prod_desc' => 'Long-lasting air fresheners in various scents, pack of 6.',
                'prod_module_from' => 'psm',
                'prod_submodule_from' => 'vendor-management',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        // Insert products
        DB::connection('psm')->table('psm_product')->insert($products);

        $this->command->info('Successfully seeded 23 products!');
        $this->command->info('Products distributed across 4 vendors:');
        $this->command->info('- EquipmentPro Solutions: 4 products');
        $this->command->info('- OfficeSupplies Depot: 6 products');
        $this->command->info('- ModernFurniture Co.: 5 products');
        $this->command->info('- AutoParts Express: 8 products');
    }
}